# Generated by Django 3.2.9 on 2021-11-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name="person's first name")),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
