# Generated by Django 3.2.9 on 2021-11-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='names of types of pizza'),
        ),
    ]
