# Generated by Django 3.2.9 on 2021-11-17 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20211117_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'topping'},
        ),
    ]
