# Generated by Django 3.2.9 on 2021-11-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_alter_topping_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='topping',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
